### ISSUE TITLE
U: Classic connectives parsed incorrectly

### ISSUE THREAD

**Issue by gburel** [Deducteam/lambdapi-logics#4]
I do not know if it is a bug in lambdapi, the priorities that have to be changed, or just the definition of the connectives that needs to be parenthesized, but the definitions of the classical connectives are badly parsed 

```
require open Logic.U.Prop Logic.U.Classic;

symbol p : Prop;
symbol q : Prop;

assertnot  ⊢ p ∧ᶜ q ≡ (¬ ¬ p) ∧ (¬ ¬ q); 
assert ⊢ p ∧ᶜ q ≡ ¬ ¬ (p ∧ (¬ ¬ q));
```

and the same for ∨ᶜ.

**Comment by fblanqui** [comment]
Thanks Guillaume to spot this mistake! This is because the precedence of negation was lower than the one of the other connectives. I propose to fix it in #6.
